spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project4?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tjddnr12
  
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: choisw950928@gmail.com
    password: tjddnr12
    properties:
      mail:
        smtp:
          starttls:
            enable: true

logging:
  level:
    root: info

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

